version: '3.5'
volumes:
  avalanche-ipcs:
services:
  mysql:
    image: "mysql:8.0.26"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - /var/lib/ortelius/mysql:/var/lib/mysql
      - ./../my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ortelius
    restart: on-failure
  migrate:
    image: "migrate/migrate:v4.14.1"
    volumes:
      - ../../services/db/migrations:/migrations
    depends_on:
      - mysql
    entrypoint: ["/bin/sh"]
    command: |
      -c 'while ! migrate -path=/migrations/ -database "mysql://root:password@tcp(mysql:3306)/ortelius" up; do
        sleep 1
      done'
    restart: on-failure
  avalanche:
    env_file:
      - production.env
    image: "hyphenesc/dijetsnode:v1.0"
    command: /bin/sh -cx "exec /avalanchego/build/avalanchego
      --config-file=/opt/config.json
      --network-id=12345
      --bootstrap-ips=51.142.74.53:9651
      --bootstrap-ids=NodeID-7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg
      --index-enabled=true
      --index-allow-incomplete=true
      "
    ports:
      - "9650:9650"
    volumes:
      - /var/lib/ortelius/avalanche:/var/lib/avalanche
      - ./../avalanchego_config.json:/opt/config.json
      - ./../avalanchego_chain_config:/opt/avalanchego
      - avalanche-ipcs:/tmp
    depends_on:
      - indexer
    restart: always
  indexer: &ortelius-app
    image: "hyphenesc/dijiindexer:v1.0"
    command: ["stream", "indexer", "-c", "/opt/config.json"]
    external_links:
      - mysql
    depends_on:
      - mysql
      - migrate
    volumes:
      - avalanche-ipcs:/tmp
      - ./../config.json:/opt/config.json
    restart: on-failure
  api:
    <<: *ortelius-app
    command: ["api", "-c", "/opt/config.json"]
    ports:
      - 8080:8080
